### ISSUE TITLE
[18w50a] Crash on Gamestart

### ISSUE THREAD

**Issue by MasterEnderman** [elytra/InfraRedstone-Fabric#4]
InfraRedstone: 1.0.1
Fabric: 0.1.3.68
Silk: 0.1.0
qcommon croco: 1.0.3
qcommon architect: 1.0.0
Crash-Report: https://pastebin.com/DwmadXqK

**Comment by Boundarybreaker** [comment]
It looks like there's a mismatch with your InfraRedstone and Silk versions. I'd recommend backdating to InfraRedstone 1.0.0; the only difference is the version of Silk it's built for, since Silk renamed one of its classes.

**Comment by LemmaEOF** [comment]
Turns out that Silk hadn't had its newest version pushed yet. That's fixed now.
