### ISSUE TITLE
Wire Search Special Cases That Should Probably Work Differently

### ISSUE THREAD

**Issue by LemmaEOF** [elytra/InfraRedstone-Fabric#5]
Because wires only search backwards, that can lead to a few oddities with how things work. We talked with the original InfraRedstone about redesigning wire search to work both backwards and forwards, with both push and pull. Here are a few odd cases that probably should work differently.

## 1. cables and scaffolds
![2019-01-09_22 37 57](https://user-images.githubusercontent.com/6722691/50950899-45160e00-1460-11e9-8681-98704664e533.png)
This is a mess both visually and functionally. Both cables connect to the scaffold visually, but the scaffold won't update its state to visually connect to either of them. On top of that, a signal can't make its way through the whole thing, because the search is either traveling upwards and won't leap from the scaffold to the upper cable, or it's traveling downwards and won't leap from the scaffold to the lower cable. However, if there's a signal coming from the side of the scaffold, both a device searching up and a device searching down will be able to find it. Personally, I think this should connect all the way through, but that would require adding diagonal checks to the scaffold, which could have other unintentional effects.

## 2. cables and inred blocks
![2019-01-09_22 41 36](https://user-images.githubusercontent.com/6722691/50951100-e43b0580-1460-11e9-96ff-643c5bdb6818.png)
Because the system is designed to let modules transfer up and forward through a block, this technically works, since the inred block outputs on all four sides. However, it looks really weird, and doesn't make all that much sense with the jacketed look inred cables have. I don't think this should connect, honestly. It just doesn't feel right with the way it's framed.

## 3. slab-stairs
![2019-01-09_23 00 00](https://user-images.githubusercontent.com/6722691/50951538-6546cc80-1462-11e9-9cff-687ee8f57889.png)
We've talked over this before, and while it looks weird, we've decided to keep it in, and that we can't really do anything to improve the look without adding a decent amount of extra code and/or blockstates.

**Comment by falkreon** [comment]
I think maybe we should agree on a `shouldConnect(World world, BlockPos from, BlockPos to)` method that takes into consideration these vagaries in-world and spits out a true or false - then the wireSearch can start with "all vertical diagonals in each cardinal direction" and prune out entries where shouldConnect is false or there's no valid inred/redstone target.

The contract would specify that reversed from/to MUST produce the same results.

Then, shouldConnect could be used for a uniform behavior between the cable appearance and the cable behavior.

It might be possible to delegate this method to the individual blocks involved, like
```java
public boolean shouldConnect(...) {
    //(... setup fromBlock and toBlock)
    return fromBlock.shouldConnect(to) && toBlock.shouldConnect(from);
}
```

**Comment by LemmaEOF** [comment]
I think the main problem with that `shouldConnect` is that it looks to not give info about block positions. Also, I'm looking through the `wireSearch` code and ~~I'm having a little trouble making sense of it. I can see where it scans up, but not where it scans down, so it seems like anything scanning backwards down a staircase wouldn't actually detect.~~ EDIT: I understand it now, so I'm gonna add in the special-cases. I've got the visuals working correctly, but I haven't yet been able to make it actually scan properly.

**Comment by LemmaEOF** [comment]
![2019-01-13_20 40 37](https://user-images.githubusercontent.com/6722691/51096731-92052780-1773-11e9-81cf-ce833326b2a8.png)
![2019-01-13_20 40 32](https://user-images.githubusercontent.com/6722691/51096732-92052780-1773-11e9-9039-637159b6e8e0.png)
![2019-01-13_20 40 27](https://user-images.githubusercontent.com/6722691/51096733-92052780-1773-11e9-8ba4-5304d1c46bc0.png)
We have success! I'm not gonna touch #3 for now since it honestly isn't really worth it, it works functionally and is too much of a niche to bother with, given that scaffolds exist.
